### PR TITLE
#167980665 Fix ReadCount stat & List users

### PR DESCRIPTION
**Pull request by obayomi96**
What does this PR do?
This PR fixes bugs on the Reading Statistics feature and Allows only admin access the list all users route

Description of Task to be completed?
-Ensures that the reading statistics tally with the database reading statistics
-Ensures that the List all Users route is only accessible to the admin

#### What are the relevant pivotal tracker stories?

#167980665

### CODE REVIEW

**Review by Hadeneekeh — APPROVED** [review]
LGTM

**Review by topseySuave — APPROVED** [review]

**Review by Lundii — APPROVED** [review]
LGTM

**Review by chiboycalix — APPROVED** [review]
LGTM

**Review by chuxmykel — APPROVED** [review]
Nice one @obayomi96. Looks Good.

**Pull request merged**
