### PR TITLE
#167190426 Setup unit test

### PR DESCRIPTION
**Pull request by cvjude**
#### What does this PR do?
- Sets up unit testing for the App

#### How can this be manually tested?
- Clone the repo
- Run the command below in your terminal to install all dependencies
```
npm install
``` 
- Run the command below to test
```
npm test
```

#### Any background context you want to provide?
none

#### What are the relevant Pivotal Tracker stories? 
- [#167190426](https://www.pivotaltracker.com/story/show/167190426)

### CODE REVIEW

**Review by obayomi96 — APPROVED** [review]
Looks good

**Review by chiboycalix — APPROVED** [review]
LGTM

**Review by Lundii — APPROVED** [review]
Test script working fine.

**Review by chuxmykel — APPROVED** [review]
LGTM

**Review by Hadeneekeh — APPROVED** [review]

**Review by encodedBicoding — APPROVED** [review]
LGTM

**Review by topseySuave — APPROVED** [review]

**Pull request merged**
