### PR TITLE
#167190440 User can perform crud operations on articles

### PR DESCRIPTION
**Pull request by chiboycalix**
#### Any background context you want to provide?
- none
#### What are the relevant pivotal tracker stories?
[#167190440](https://www.pivotaltracker.com/story/show/167190440)
#### Screenshots (if appropriate)

Screenshot 2019-07-31 at 1 26 07 PM

### CODE REVIEW

**Review by encodedBicoding — APPROVED** [review]
LGTM

**Review by chuxmykel — COMMENTED** [review]
Fix the hound issues and you're good to go.

**Review by chuxmykel — APPROVED** [review]
Nice one @chiboycalix. LGTM

**Review by Lundii — APPROVED** [review]
Nice work Nonso. LGTM

**Review by obayomi96 — APPROVED** [review]
LGTM

**Review by topseySuave — APPROVED** [review]

**Comment by topseySuave** [comment]
You are declaring `validateLogin` twice.

**Pull request merged**
