### PR TITLE
Users should be able to view all their articles

### PR DESCRIPTION
**Pull request by chiboycalix**

### CODE REVIEW

**Review by Lundii — APPROVED** [review]
LGTM

**Review by Hadeneekeh — APPROVED** [review]
LGTM

**Review by chuxmykel — APPROVED** [review]
Looks good to me.

**Review by encodedBicoding — APPROVED** [review]
LGTM. Thanks for your initiative towards this.

**Review by obayomi96 — APPROVED** [review]
LGTM

**Pull request merged**
