### PR TITLE
#168456837 Users can recieve follow notifications

### PR DESCRIPTION
**Pull request by cvjude**
#### What does this PR do?
- Users can receive follow notifications

#### How can this be manually tested?
- Clone the repo
- Run the command below in your terminal to install all dependencies
```
npm install
``` 
- Run the command below to test
```
npm test
```

#### Any background context you want to provide?
none

#### What are the relevant Pivotal Tracker stories? 
- [#168456837](https://www.pivotaltracker.com/story/show/168456837)

### CODE REVIEW

**Review by Hadeneekeh — APPROVED** [review]
LGTM

**Review by Lundii — APPROVED** [review]
LGTM

**Review by chuxmykel — APPROVED** [review]
Looks Good @cvjude. Nice work

**Review by chiboycalix — APPROVED** [review]
LGTM

**Review by obayomi96 — APPROVED** [review]
LGTM

**Pull request merged**
